import * as Dialog from '@radix-ui/react-dialog';
import { CalendarDays, ChevronLeft, ChevronRight, Code2, ExternalLink, LoaderCircle, Palette, Plus, RefreshCw, Settings2, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { CalendarGlyph, calendarColor, calendarIconChoices } from './CalendarGlyph';
import { addDays, dateKey, meetingDate, meetingTime, startOfWeek, weekRangeLabel } from './calendarUtils';
import { api, Calendar, calendarAPI, Meeting, parseTags, RuntimeConfig, Status, Tag as CalendarTag, Tool } from './api';

type Page = 'calendar' | 'config' | 'api';
const nav: Array<{ id: Page; label: string; icon: typeof Settings2 }> = [{ id: 'calendar', label: 'Calendar', icon: CalendarDays }, { id: 'config', label: 'Config', icon: Settings2 }, { id: 'api', label: 'API', icon: Code2 }];

export function App() {
  const [page, setPage] = useState<Page>('calendar'); const [status, setStatus] = useState<Status>(); const [calendars, setCalendars] = useState<Calendar[]>([]); const [tags, setTags] = useState<CalendarTag[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [addOpen, setAddOpen] = useState(false); const [refreshing, setRefreshing] = useState(false);
  const reload = async () => { setLoading(true); try { const [nextStatus, nextCalendars, nextTags] = await Promise.all([api<Status>('/api/status'), calendarAPI.list(), calendarAPI.tags()]); setStatus(nextStatus); setCalendars(nextCalendars); setTags(nextTags); setError(''); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load ICS MCP'); } finally { setLoading(false); } };
  useEffect(() => { void reload(); }, []);
  const refreshAll = async () => { setRefreshing(true); try { await calendarAPI.refreshAll(); await reload(); } finally { setRefreshing(false); } };
  return <div className="app-shell"><header className="toolbar"><button className="brand" onClick={() => setPage('calendar')}><span className="brand-mark">IC</span><span><strong>ICS MCP</strong><small>Calendar workspace</small></span><code>v{status?.version.version || '…'}</code></button><nav aria-label="Primary navigation">{nav.map(item => { const Icon = item.icon; return <button key={item.id} className={page === item.id ? 'nav-link active' : 'nav-link'} onClick={() => setPage(item.id)}><Icon size={16}/>{item.label}</button>; })}</nav><div className="toolbar-actions"><span className="timezone">{status?.timezone || 'Loading timezone…'}</span><button className="button secondary" onClick={() => void refreshAll()} disabled={refreshing}>{refreshing ? <LoaderCircle className="spin" size={16}/> : <RefreshCw size={16}/>}Refresh</button><button className="button primary" onClick={() => setAddOpen(true)}><Plus size={17}/>Add calendar</button></div></header><main>{error && <div className="notice error"><X size={16}/>{error}<button onClick={() => void reload()}>Try again</button></div>}{loading && !status ? <LoadingPage/> : <>{page === 'calendar' && <CalendarWorkspace calendars={calendars} timezone={status?.timezone}/>} {page === 'config' && <Config calendars={calendars} tags={tags} reload={reload}/>} {page === 'api' && <APIWorkspace/>}</>}</main><AddCalendar open={addOpen} onOpenChange={setAddOpen} tags={tags} onAdded={reload}/></div>;
}

function LoadingPage() { return <div className="loading-page"><LoaderCircle className="spin" size={28}/><p>Loading your calendar…</p></div>; }
function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>; }

function CalendarWorkspace({ calendars, timezone }: { calendars: Calendar[]; timezone?: string }) {
  const [week, setWeek] = useState(() => startOfWeek(new Date())); const [meetings, setMeetings] = useState<Meeting[]>([]); const [selected, setSelected] = useState<Meeting>(); const [loading, setLoading] = useState(true);
  useEffect(() => { const after = week.toISOString(); const before = addDays(week, 7).toISOString(); setLoading(true); api<Meeting[]>(`/api/meetings?detail=full&limit=500&after=${encodeURIComponent(after)}&before=${encodeURIComponent(before)}&sort=start_time`).then(setMeetings).finally(() => setLoading(false)); }, [week]);
  const calendarByID = useMemo(() => new Map(calendars.map(calendar => [calendar.id, calendar])), [calendars]); const days = Array.from({ length: 7 }, (_, index) => addDays(week, index)); const today = dateKey(new Date());
  return <><PageHeader eyebrow="WEEKLY CALENDAR" title={weekRangeLabel(week)} description={`Your default query calendars · ${timezone || 'server timezone'}`} action={<div className="calendar-controls"><button className="icon-button" title="Previous week" onClick={() => setWeek(addDays(week, -7))}><ChevronLeft size={18}/></button><button className="button secondary" onClick={() => setWeek(startOfWeek(new Date()))}>Today</button><button className="icon-button" title="Next week" onClick={() => setWeek(addDays(week, 7))}><ChevronRight size={18}/></button></div>}/><section className="calendar-layout"><div className="week-card"><div className="week-header">{days.map(day => <div className={dateKey(day) === today ? 'day-heading today' : 'day-heading'} key={dateKey(day)}><span>{day.toLocaleDateString(undefined, { weekday: 'short' })}</span><strong>{day.getDate()}</strong></div>)}</div>{loading ? <LoadingPage/> : <div className="week-grid">{days.map(day => <DayColumn key={dateKey(day)} day={day} meetings={meetings.filter(meeting => meetingDate(meeting) === dateKey(day))} calendarByID={calendarByID} selected={selected} onSelect={setSelected}/>)}</div>}</div><aside className="agenda-panel"><div><span className="eyebrow">DETAILS</span><h2>{selected ? selected.name : 'Select an event'}</h2></div>{selected ? <EventDetails meeting={selected} calendar={calendarByID.get(selected.calendar_id || '')}/> : <><p>Choose an event to see its time, calendar, and joining link.</p><div className="calendar-key">{calendars.map(calendar => <div key={calendar.id}><CalendarGlyph icon={calendar.icon} color={calendarColor(calendar)}/><span>{calendar.name}</span></div>)}</div></>}</aside></section></>;
}

function DayColumn({ day, meetings, calendarByID, selected, onSelect }: { day: Date; meetings: Meeting[]; calendarByID: Map<string, Calendar>; selected?: Meeting; onSelect: (meeting: Meeting) => void }) { return <div className="day-column">{meetings.length === 0 && <span className="day-empty">No events</span>}{meetings.map(meeting => { const calendar = calendarByID.get(meeting.calendar_id || ''); const color = calendar ? calendarColor(calendar) : '#4f8f72'; return <button className={selected === meeting ? 'event-card selected' : 'event-card'} style={{ '--event-color': color } as React.CSSProperties} onClick={() => onSelect(meeting)} key={`${meeting.calendar_id}-${meeting.name}-${meeting.start}-${meeting.date}`}><span>{meetingTime(meeting)}</span><strong>{meeting.name}</strong><small>{calendar?.name || meeting.calendar_name || 'Calendar'}</small></button>; })}</div>; }
function EventDetails({ meeting, calendar }: { meeting: Meeting; calendar?: Calendar }) { return <div className="event-details"><div className="event-detail-title"><CalendarGlyph icon={calendar?.icon} color={calendar ? calendarColor(calendar) : '#4f8f72'} size={22}/><span>{calendar?.name || meeting.calendar_name}</span></div><strong>{meetingTime(meeting)}</strong><p>{meeting.date}</p>{meeting.meeting_url && <a className="button primary" href={meeting.meeting_url} target="_blank" rel="noreferrer"><ExternalLink size={16}/>Join meeting</a>}</div>; }

function Config({ calendars, tags, reload }: { calendars: Calendar[]; tags: CalendarTag[]; reload: () => Promise<void> }) { const [section, setSection] = useState<'settings' | 'calendars'>('settings'); return <><PageHeader eyebrow="CONFIGURATION" title="Settings and calendars" description="Runtime settings and calendar presentation live together here."/><div className="config-tabs"><button className={section === 'settings' ? 'active' : ''} onClick={() => setSection('settings')}>Runtime settings</button><button className={section === 'calendars' ? 'active' : ''} onClick={() => setSection('calendars')}>Calendars <b>{calendars.length}</b></button></div>{section === 'settings' ? <RuntimeSettings/> : <CalendarInventory calendars={calendars} tags={tags} reload={reload}/>}</>; }

function RuntimeSettings() { const [config, setConfig] = useState<RuntimeConfig>(); const [saving, setSaving] = useState(''); const reload = () => api<RuntimeConfig>('/api/config').then(setConfig); useEffect(() => { void reload(); }, []); const save = async (key: keyof RuntimeConfig, value: string | boolean) => { setSaving(String(key)); try { await api<RuntimeConfig>('/api/config', { method: 'PUT', body: JSON.stringify({ [key]: value }) }).then(setConfig); } finally { setSaving(''); } }; if (!config) return <LoadingPage/>; const fields: Array<[keyof RuntimeConfig, string, string, 'text' | 'checkbox']> = [['refresh_interval', 'Refresh interval', 'How often ICS feeds are refreshed.', 'text'], ['timezone', 'Display timezone', 'Used for meetings and this calendar view.', 'text'], ['external_url', 'External URL', 'Used in setup instructions and client snippets.', 'text'], ['update_check', 'Release checks', 'Periodically check for a newer ICS MCP release.', 'checkbox']]; return <section className="settings-grid">{fields.map(([key, label, hint, kind]) => { const source = config.sources[key] || 'default'; const locked = source !== 'database' && source !== 'default'; const value = config[key]; return <article className="setting-card" key={String(key)}><div><h2>{label}</h2><p>{hint}</p><span className={locked ? 'source-lock' : 'source'}>{locked ? `Overridden by ${source}` : `Source: ${source}`}</span></div><div className="setting-control">{kind === 'checkbox' ? <input type="checkbox" checked={Boolean(value)} disabled={locked} onChange={event => void save(key, event.target.checked)}/> : <input defaultValue={String(value)} disabled={locked} onBlur={event => { if (event.target.value !== String(value)) void save(key, event.target.value); }}/>} {saving === key && <LoaderCircle className="spin" size={16}/>}</div></article>; })}</section>; }

function CalendarInventory({ calendars, tags, reload }: { calendars: Calendar[]; tags: CalendarTag[]; reload: () => Promise<void> }) { const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Calendar>(); const [busyID, setBusyID] = useState(''); const filtered = calendars.filter(calendar => calendar.name.toLowerCase().includes(query.toLowerCase())); const refresh = async (id: string) => { setBusyID(id); try { await calendarAPI.refresh(id); await reload(); } finally { setBusyID(''); } }; const remove = async (calendar: Calendar) => { if (window.confirm(`Remove ${calendar.name} and its cached events?`)) { await calendarAPI.remove(calendar.id); await reload(); } }; return <><section className="inventory-toolbar"><label className="search"><span>Search</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Find a calendar"/></label><span>{tags.length} tag groups</span></section><section className="calendar-inventory">{filtered.map(calendar => <article className="calendar-row" key={calendar.id}><CalendarGlyph icon={calendar.icon} color={calendarColor(calendar)} size={28}/><div className="calendar-row-main"><strong>{calendar.name}</strong><small>{calendar.key} · {calendar.event_count} cached events</small><div className="tag-list">{calendar.tags.map(tag => <span className="tag-chip" key={tag}>{tag}</span>)}</div></div><div className="calendar-row-actions"><button className={calendar.include_in_general_queries ? 'selection-pill selected' : 'selection-pill'} onClick={() => void calendarAPI.update(calendar.id, { include_in_general_queries: !calendar.include_in_general_queries }).then(reload)}>Default query</button><button className="icon-button" title="Refresh calendar" disabled={busyID === calendar.id} onClick={() => void refresh(calendar.id)}><RefreshCw className={busyID === calendar.id ? 'spin' : ''} size={16}/></button><button className="button secondary" onClick={() => setEditing(calendar)}>Edit</button><button className="icon-button danger-button" title="Remove calendar" onClick={() => void remove(calendar)}><X size={16}/></button></div></article>)}</section>{editing && <CalendarEditor calendar={editing} tags={tags} onClose={() => setEditing(undefined)} onSaved={async () => { await reload(); setEditing(undefined); }}/>}</>; }

function CalendarEditor({ calendar, tags, onClose, onSaved }: { calendar: Calendar; tags: CalendarTag[]; onClose: () => void; onSaved: () => Promise<void> }) { const [name, setName] = useState(calendar.name); const [tagText, setTagText] = useState(calendar.tags.join(', ')); const [color, setColor] = useState(calendarColor(calendar)); const [icon, setIcon] = useState(calendar.icon || 'calendar'); const [saving, setSaving] = useState(false); const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await calendarAPI.update(calendar.id, { name, tags: parseTags(tagText), color, icon }); await onSaved(); } finally { setSaving(false); } }; return <CalendarDialog title={`Edit ${calendar.name}`} description="Presentation metadata is used in the calendar workspace." onClose={onClose}><form onSubmit={save}><label>Name<input value={name} onChange={event => setName(event.target.value)}/></label><label>Tags<input value={tagText} onChange={event => setTagText(event.target.value)} list="tag-suggestions"/><datalist id="tag-suggestions">{tags.map(tag => <option key={tag.name} value={tag.name}/>)}</datalist></label><VisualPicker color={color} setColor={setColor} icon={icon} setIcon={setIcon}/><DialogActions saving={saving} label="Save changes" onClose={onClose}/></form></CalendarDialog>; }

function AddCalendar({ open, onOpenChange, tags, onAdded }: { open: boolean; onOpenChange: (open: boolean) => void; tags: CalendarTag[]; onAdded: () => Promise<void> }) { const [name, setName] = useState(''); const [url, setURL] = useState(''); const [tagText, setTagText] = useState(''); const [color, setColor] = useState('#4f8f72'); const [icon, setIcon] = useState('calendar'); const [saving, setSaving] = useState(false); const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await calendarAPI.add({ name, url, tags: parseTags(tagText), color, icon }); await onAdded(); setName(''); setURL(''); setTagText(''); onOpenChange(false); } finally { setSaving(false); } }; return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog"><Dialog.Title>Add a calendar</Dialog.Title><Dialog.Description>Choose a color and MDI icon so it is easy to recognize in your calendar.</Dialog.Description><form onSubmit={save}><label>Name<input required value={name} onChange={event => setName(event.target.value)} placeholder="Work"/></label><label>ICS URL<input required type="url" value={url} onChange={event => setURL(event.target.value)} placeholder="https://…/calendar.ics"/></label><label>Tags<input value={tagText} onChange={event => setTagText(event.target.value)} placeholder="Work, Personal"/></label><VisualPicker color={color} setColor={setColor} icon={icon} setIcon={setIcon}/><div className="dialog-actions"><Dialog.Close asChild><button type="button" className="button secondary">Cancel</button></Dialog.Close><button className="button primary" disabled={saving}>{saving && <LoaderCircle className="spin" size={16}/>}Add calendar</button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>; }

function CalendarDialog({ title, description, onClose, children }: { title: string; description: string; onClose: () => void; children: React.ReactNode }) { return <Dialog.Root open onOpenChange={open => { if (!open) onClose(); }}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog"><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
function VisualPicker({ color, setColor, icon, setIcon }: { color: string; setColor: (value: string) => void; icon: string; setIcon: (value: string) => void }) { return <fieldset className="visual-picker"><legend><Palette size={15}/>Appearance</legend><label className="color-control">Color<input type="color" value={color} onChange={event => setColor(event.target.value)}/><code>{color}</code></label><div className="icon-picker">{calendarIconChoices.map(choice => <button type="button" className={icon === choice ? 'icon-choice active' : 'icon-choice'} title={choice} onClick={() => setIcon(choice)} key={choice}><CalendarGlyph icon={choice} color={color}/></button>)}</div></fieldset>; }
function DialogActions({ saving, label, onClose }: { saving: boolean; label: string; onClose: () => void }) { return <div className="dialog-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={saving}>{saving && <LoaderCircle className="spin" size={16}/>} {label}</button></div>; }
function APIWorkspace() { const [tools, setTools] = useState<Tool[]>([]); useEffect(() => { api<Tool[]>('/api/tools').then(setTools); }, []); return <><PageHeader eyebrow="API" title="Integration workspace" description="Inspect available MCP tools without leaving the admin console."/><section className="panel tool-directory">{tools.map(tool => <article key={tool.name}><Code2 size={18}/><div><strong>{tool.name}</strong><p>{tool.description}</p></div></article>)}</section></>; }
